### ISSUE TITLE
Stremio Add on no sound

### ISSUE THREAD

**Issue by safdar9633** [Flixclusive/flx-providers#10]
While playing some  movies using stremio + Torrentio + RD , there us no sound. When i change to a different video it has sound. Checked the same with stremio app and cloudstream there is sound. What might be the issue here?

**Comment by rhenwinch** [comment]
May I ask what show/movie you're trying to play?

**Comment by safdar9633** [comment]
Its not just 1 Show/movie there is a lot having same issues. Lets take House of dragon season 1 Episode 1. There is RD+ link which i am trying to play. It plays bit no sound.

**Comment by rhenwinch** [comment]
> There is RD+ link which i am trying to play. It plays bit no sound.

Idk, but my end (both my physical device and emulators) can play the said show seamlessly. Is there an audio item that appears on the Audio section of _"Audio & Subtitles"_ dialog?

**Comment by safdar9633** [comment]
Yes it says Track 1. I have tried many other and same problem. Maybe problem is with my phone i think

**Comment by rhenwinch** [comment]
Oof. Media3 might be buggy on your device if that's the case.

**Comment by rhenwinch** [comment]
Will re-open this issue if I get another concern about this. This somehow piqued my interest, I kinda have a solution in mind I just dont have the right amount of evidences yet

**Comment by rhenwinch** [comment]
Fixing this on the app currently.
