### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by NeupanePawan97** [Flixclusive/flx-providers#11]
I don't know why but my stremio extension isn't working, Am I missing something?

**Comment by rhenwinch** [comment]
is your stremio extension public? if yes, may I have its manifest link? I will test it on my end.

**Comment by NeupanePawan97** [comment]
It is torrentio, I tried to just test as I didn't know how it was supposed to work, here's the manifest link:
stremio://torrentio.strem.fun/providers=yts,eztv,rarbg,1337x,thepiratebay,kickasstorrents,torrentgalaxy,magnetdl,horriblesubs,nyaasi,tokyotosho,anidex%7Clanguage=hindi%7Cqualityfilter=dolbyvision,dolbyvisionwithhdr,threed,4k,scr,cam,unknown/manifest.json

**Comment by NeupanePawan97** [comment]
Yea so that's what I've been missing, now it's working 😀 thanks pal
