### ISSUE TITLE
Superstream

### ISSUE THREAD

**Issue by napacia** [Flixclusive/flx-providers#13]
I'm so glad it's back, but I've been encountering a problem. The previous version of SuperStream loaded very quickly; I could skip a large part of a video without any buffering. However, the current version takes too much time to load and buffers every three seconds. Thoughts?

**Comment by rhenwinch** [comment]
> previous version

Do you mean the old _old_ SuperStream? If so, they changed their security and added authorization.

**Comment by napacia** [comment]
oh is that so... I was really wondering how it suddenly became slow, considering it used to load very quickly without any buffering, but maybe that's just how it is... thanks for answering 🙏🏻
