### ISSUE TITLE
Debrid search catalog addon stremio support

### ISSUE THREAD

**Issue by oathzed** [Flixclusive/flx-providers#14]
Hello,

I saw you recently added support for catalog add-ons. Is it possible to support debrid search fully? Basically it shows what you've added to your debrid cloud. It has to pair with an addon like torentio. I believe it also searches your cloud and displays links when you click an episode. Currently it's just blank:
![Screenshot_20240622-104618](https://github.com/Flixclusive/flx-providers/assets/52545913/13e6c0fa-f568-4040-bc49-83762c547d1c)

Thank you!

**Comment by rhenwinch** [comment]
Hi,

I've checked also on Torrentio's debrid catalog I think the problem is that the catalogs return a type of "other" instead of "movie" and "series". I'll look at it tomorrow. Thanks for the heads up

**Comment by oathzed** [comment]
> Hi,
> 
> I've checked also on Torrentio's debrid catalog I think the problem is that the catalogs return a type of "other" instead of "movie" and "series". I'll look at it tomorrow. Thanks for the heads up

Copy that. Ty sir!

**Comment by rhenwinch** [comment]
Has this been fixed after the recent commits?

**Comment by oathzed** [comment]
> Has this been fixed after the recent commits?

Yee it works! Just tested with RD. I guess it bo longer works on AD.. I'll ask the dev if he can fix it. Thank you!

**Comment by oathzed** [comment]
> > Has this been fixed after the recent commits?
> 
> Yee it works! Just tested with RD. I guess it bo longer works on AD.. I'll ask the dev if he can fix it. Thank you!

It searches the debrid search when you scrape an episode fine. But actually looking at the catalog itself and trying to play something doesn't actually work which is kinda dumb. But it also doesn't work in stremio itself

**Comment by rhenwinch** [comment]
Ah. The search issue is not yet up for grabs in the app. Only the home catalogs are ready to use features for now

**Comment by oathzed** [comment]
> Ah. The search issue is not yet up for grabs in the app. Only the home catalogs are ready to use features for now
> 
> Feel free to reopen this one

Maybe were talking about different things, but when I open up an episode of let's say stranger things s01e01 and click play, it will find the link in my debrid search and play it.

Or are you talking about when you use the actual search bar and it shows whatever you search is in your debrid cloud?

Will reopen
