### ISSUE TITLE
Knightcrawler stremio addon not working

### ISSUE THREAD

**Issue by oathzed** [Flixclusive/flx-providers#15]
Hello, the knightcrawler addon doesn't seem to pull any links, it's a similar addon to torentio. I'm using alldebrid for testing:
https://torrentio.elfhosted.com/configure

Cheers!

**Comment by rhenwinch** [comment]
There might be a problem on their 'stream' resource. I tried fetching them manually, it doesn't load. May I ask if you've tried this on Stremio directly? Does it work?

**Comment by oathzed** [comment]
> There might be a problem on their 'stream' resource. I tried fetching them manually, it doesn't load. May I ask if you've tried this on Stremio directly? Does it work?
> 
> ![image](https://private-user-images.githubusercontent.com/52451354/342329952-d022158a-b581-4220-8fb6-518683df5e87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDExMDgsIm5iZiI6MTcxOTI0MDgwOCwicGF0aCI6Ii81MjQ1MTM1NC8zNDIzMjk5NTItZDAyMjE1OGEtYjU4MS00MjIwLThmYjYtNTE4NjgzZGY1ZTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE0NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwM2I0NTc4ODMxN2JkNGM0MWU3NjM2MGFmZjcxMGI1NzFjOWI2MTQxMWIzZDRjM2E0OWViMDdlYTIxYTAzMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQ0-zp8Ia9rpsJ9NlvabdrVM9JoyNqxHRgsgfTjxjRs)

Interesting. Yes I've tested on stremio and it works just fine

**Comment by rhenwinch** [comment]
Just tested it out on the current version. It seems to be fine.

**Comment by oathzed** [comment]
> Just tested it out on the current version. It seems to be fine.

My bad.. I should have double check I was on the latest version.. it does seem to work. Thank you!
