### ISSUE TITLE
Dubbed Audio

### ISSUE THREAD

**Issue by adilurrhmn** [Flixclusive/flx-providers#19]
### Provider information

SuperStream

### Steps to reproduce

There is no hindi dubbed Audio for English movies only English audio is available.

### Flixclusive version

2.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by rhenwinch** [comment]
Should there be dubbed audios on that provider?
