### ISSUE TITLE
Stremio addons install

### ISSUE THREAD

**Issue by oathzed** [Flixclusive/flx-providers#2]
In seeing that the stremio addon is in beta so forgive me if you're still working on this part.

I try to add the install url of an addon to flixclusive but it doesn't let me (this carries all the settings, API key etc.), but it does let me paste the actual addon url which doesn't seem to show me any settings to change. I'm just wondering, wouldn't it be easiest to let us add the install url instead so everything can be handled outside flixclusive. Add-ons tested: torrentio, jamovies

Thanks! ❤️

**Comment by rhenwinch** [comment]
do you mean the links with the `stremio://` protocol? If so, then sorry for that it was supposed to catch those types of links, but the regex didn't. My fault lol, expect a fix soon.

Also, RealDebrid + Torrentio works magically!

**Comment by oathzed** [comment]
> do you mean the links with the `stremio://` protocol? If so, then sorry for that it was supposed to catch those types of links, but the regex didn't. My fault lol, expect a fix soon.
> 
> Also, RealDebrid + Torrentio works _magically_!

That's correct. No worries! Awesome, looking forward to trying it out!

**Comment by rhenwinch** [comment]
fixed on 1c72d58
