### ISSUE TITLE
New Provider

### ISSUE THREAD

**Issue by adilurrhmn** [Flixclusive/flx-providers#21]
### Provider name

Hindi dubbed movies and series 

### Provider URL

Vegamovies, luxmovies 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by rhenwinch** [comment]
hello,

it's already been raised here on a duplicate issue.

duplicate of #20

**Comment by rhenwinch** [comment]
duplicate of #20

**Comment by rhenwinch** [comment]
Duplicate of #20
