### ISSUE TITLE
No Hindi Dubbed Audio

### ISSUE THREAD

**Issue by adilurrhmn** [Flixclusive/flx-providers#23]
### Provider information

SuperStream, Sudo flix

### Flixclusive version

1.3.0, 1.3.2

### Other details

No Hindi Dubbed available on the provider. Please add atleast one provider that contain multi audio support 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by rhenwinch** [comment]
This is not an issue. If providers dont have dubbed audios, then that is simply it. _It is what it is_

There's been a provider request for hindi links. Its already been issued.

**Comment by rhenwinch** [comment]
#8 and #17 for hindi providers.

**Comment by rhenwinch** [comment]
Also, you already issued the same concern.

Duplicate of #19
