### ISSUE TITLE
Sudo flix stop working, Please add this provider

### ISSUE THREAD

**Issue by adilurrhmn** [Flixclusive/flx-providers#26]
### Provider name

Vidbinge

### Provider URL

https://www.vidbinge.com/

### Package type

Movies , tv series, anime

### Provider language

en

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by rhenwinch** [comment]
I believe the current sudo-flix we have already implements that.

**Comment by adilurrhmn** [comment]
Yes, working now. But Vidbinge is better. Most sudoflix source not working
