### ISSUE TITLE
just a question 🤲🏻

### ISSUE THREAD

**Issue by napacia** [Flixclusive/flx-providers#27]
### Provider name

...

### Provider URL

...

### Other details

not really app related , idk how else to ask you but is there a possibility for you to turn superstream into a stremio addon as well? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by rhenwinch** [comment]
Hi,

Im sorry, but I can't. I dont really have the time to learn Stremio SDK and my current focus rn is the providers system of the app. 🫡
