### ISSUE TITLE
Jamovies stremio addon not pulling links

### ISSUE THREAD

**Issue by oathzed** [Flixclusive/flx-providers#3]
Hey,

Any idea why this addon doesn't pull links inside flixclusive: https://eja-addon.vercel.app/

I installed it like this:

https://eja-addon.vercel.app/manifest.json

It's not a catalogue addon, just streaming :o

**Comment by rhenwinch** [comment]
hotfix uploaded. it should automatically update on your end

also, it uses NSBX. Sometimes it works, sometimes not.

**Comment by oathzed** [comment]
> hotfix uploaded. it should automatically update on your end
> 
> also, it uses NSBX. Sometimes it works, sometimes not.

Ty sir. Yeh I guess recently that addon stopped really working, I'll post an issue on his GitHub, hopefully he can sort it out
