### ISSUE TITLE
SuperStream Bug

### ISSUE THREAD

**Issue by GrozaOP** [Flixclusive/flx-providers#5]
Not Working

**Comment by GrozaOP** [comment]
![Uploading Screenshot_20240613-165502_Flixclusive.jpg…]()

**Comment by rhenwinch** [comment]
The image above doesn't load. Could you please re-upload it?

**Comment by GrozaOP** [comment]
![Uploading Screenshot_20240614-122210_Flixclusive Beta.jpg…]()

**Comment by GrozaOP** [comment]
![Uploading Screenshot_20240614-122210_Flixclusive Beta.jpg…]()

**Comment by GrozaOP** [comment]
![Screenshot_20240614-122210_Flixclusive](https://github.com/Flixclusive/flx-providers/assets/171274638/c5a88a81-6ae9-4709-bc64-562b42a26af8)

**Comment by GrozaOP** [comment]
How to fix this Problem

**Comment by GrozaOP** [comment]
![Screenshot_20240614-123442_Flixclusive](https://github.com/Flixclusive/flx-providers/assets/171274638/c23d884e-f5ea-48c1-823d-f533b9761a71)

**Comment by GrozaOP** [comment]
This is the issue bro how to fix it

**Comment by rhenwinch** [comment]
Will look at it later.

**Comment by rhenwinch** [comment]
fixed! in case the player starts, and no links were loaded. I'll update a safe switch on the app so this instance won't happen.

**Comment by ItzNuggetz** [comment]
Hii as there's already an issue raised for Superstream, I would like to add that there's a lot of buffering time for this particular provider. In its previous releases it used to play and the buffering time was less but now it buffers every now and then and doesn't work at all.

**Comment by rhenwinch** [comment]
@ItzNuggetz 

This version of SuperStream is not the same as it was before. Its a different endpoint hence the lagging and dead links. I cant do nothing about it since the original version had upgraded their security

**Comment by ItzNuggetz** [comment]
Any workarounds or including sora stream for that matter. Your thoughts?

**Comment by rhenwinch** [comment]
> Any workarounds or including sora stream for that matter. Your thoughts? 

Could you make another provider request for this? SoraStream has been planned, but it's really a big set of source providers so its a big work
