### ISSUE TITLE
CANNOT ADD STREMIO ADD ONS

### ISSUE THREAD

**Issue by safdar9633** [Flixclusive/flx-providers#6]
Hello I cannot ad any stremio add ons. I have tried to copy the .json link from Stremio for torrentio and media fusion but it didnt work. Can you please guide how to add them?

**Comment by rhenwinch** [comment]
What add on are you trying to add?

Note that catalog addons arent supported yet.

The way to add them is just paste the link of the addon you want.

For example:
```
https://shluflix.elfhosted.com/manifest.json
stremio://torrentio.strem.fun/manifest.json
https://torrentio.strem.fun/
```

The links above are valid formats. It would be parsed and added by the provider automatically.

**Comment by rhenwinch** [comment]
Have I fix this @safdar9633? If I did, feel free to close this one.
